---
# WORDPRESS CONFIGURATIONS
# This role is a custom Ansible Role developed by the SMC team.
# Sets up WordPress related configurations.
# 
# https://github.com/darthwade/ansible-role-wordpress/blob/master/tasks/main.yml
# https://stackoverflow.com/questions/18352682/correct-file-permissions-for-wordpress

# WP CLI
- name: Check if wp-cli is installed
  stat: path=/usr/local/bin/wp
  register: wp_file

# Install wp-cli if file isn't located
- name: download wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp
  when: not wp_file.stat.exists

- name: update permissions of wp-cli to allow anyone to execute it
  file: path=/usr/local/bin/wp mode=0755

# WP permissions
- name: Create www directory
  file: state=directory path="{{ item }}" owner=deploy group=deploy mode=0755 recurse=yes
  with_items:
    - /var/www
    - /var/www/html

# WP cache
- name: Create cache directory
  file: state=directory path=/var/cache/nginx owner=root group=root

- name: File permissions
  command: find /var/www/html/ -type f -exec chmod 644 {} \;

- name: Create WordPress database
  mysql_db: name=chappress_vm login_user=root state=present
  when: isVirtualMachine

- name: Create WordPress database user
  mysql_user: name=bloguser password=password priv=chappress_vm.*:ALL host='localhost' state=present
  when: isVirtualMachine

# IS&T sets AllowUsers in sshd config by default. So let's go with that and add
# that line with current ansible and app users.
# Source: https://stackoverflow.com/a/31436781/6763239
# See also: https://github.com/chapmanu/imposter/blob/development/devops/ansible/roles/ssh/tasks/main.yml
- name: Add users to sshd_config AllowUsers line
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ ansible_user }} {{ app_user }} root"
  become: yes
  notify: Reload ssh service

# Gives the server privileges to write to WordPress directory
- name: Adding existing nginx user to group deploy
  user: name=nginx
        shell=/bin/bash
        groups=deploy
        append=yes
        
# SERVER Config
- name: Create sites directory
  file: state=directory path="{{ item }}" owner=root group=root
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Copy server templates for WordPress
  template: src={{item.src}} dest={{item.dest}}
  with_items:
      - { src: 'restrictions.conf.j2',  dest: '/etc/nginx/conf.d/restrictions.conf' }
      - { src: 'ssl.conf.j2',           dest: '/etc/nginx/conf.d/ssl.conf' }
      - { src: 'wordpress.conf.j2',  dest: '/etc/nginx/conf.d/wordpress.conf' }
      - { src: 'nginx.conf.j2',         dest: '/etc/nginx/nginx.conf' }
      - { src: 'chappress-staging.conf.j2', dest: '/etc/nginx/sites-available/chappress-staging.conf' }

- name: Symlink to sites-enabled
  file: 
    src: /etc/nginx/sites-available/chappress-staging.conf
    dest: /etc/nginx/sites-enabled/chappress-staging.conf
    state: link
  notify: Restart nginx
