#!/usr/bin/env ansible-playbook
---

- debug: msg="=> Enter configure stage"

# Debian & Ubuntu.
- stat: path=/etc/php/{{ apt_php_version }}/fpm/php.ini
  register: phpfpm_ubuntu

- include: php-fpm-ubuntu.yml
  when: phpfpm_ubuntu.stat.exists

- stat: path=/etc/php/{{ apt_php_version }}/cli/php.ini
  register: phpcli_ubuntu

- include: php-cli-ubuntu.yml
  when: phpcli_ubuntu.stat.exists

# CentOS.
#- name: delegate to SELINUX handling subtask, if necessary
#  include: set-selinux.yml
#  when: php_in_selinux is defined and php_in_selinux == true

- stat: path=/etc/php-fpm.conf
  register: phpfpm_centos

- include: php-fpm-centos.yml
  when: phpfpm_centos.stat.exists

## vim:ft=ansible :
