#!/usr/bin/env ansible-playbook
---

- debug: msg="==> Setting php-cli on Debian"

- name: Ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php/{{ apt_php_version }}/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ php_timezone }}'

- name: Enabling opcache cli
  lineinfile: dest=/etc/php/{{ apt_php_version }}/cli/php.ini
              regexp=';?opcache.enable_cli='
              line='opcache.enable_cli=1'

# vim:ft=ansible :
