#!/usr/bin/env ansible-playbook
---

- debug: msg="==> Setting php-fpm on Debian system"

# setting the php.ini .
- name: Set the php.ini
  template:
    src: templates/php.ini.ubuntu.j2
    dest: /etc/php/{{ apt_php_version }}/fpm/php.ini
    owner: root
    group: root
    mode: 644
  notify: restart php7-fpm

# setting the www.conf .
- name: Set permissions on socket - owner
  lineinfile: >
    dest=/etc/php/{{ apt_php_version }}/fpm/pool.d/www.conf
    regexp='^;?listen.owner'
    line='listen.owner = {{ php_owner }}'
    state=present

- name: Set permissions on socket - group
  lineinfile: >
    dest=/etc/php/{{ apt_php_version }}/fpm/pool.d/www.conf
    regexp='^;?listen.group'
    line='listen.group = {{ php_group }}'
    state=present

- name: Set permissions on socket - mode
  lineinfile: >
    dest=/etc/php/{{ apt_php_version }}/fpm/pool.d/www.conf
    regexp='^;?listen.mode'
    line='listen.mode = 0660'
    state=present
  notify: restart php7-fpm

# vim:ft=ansible :
