---
# SSH setup
- name: Create .ssh directory
  file: state=directory path=~/.ssh owner=deploy group=deploy mode=0700

# This will do the ssh-copy-id step for current user so cap can deploy.
# Other devs will need to look up deploy user password in PassPack and run ssh-copy-id.
- name: Set authorized key for remote user copying it from current user
  authorized_key:
    user: "{{ app_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  become: yes

# IS&T sets AllowUsers in sshd config by default. So let's go with that and add
# that line with current ansible and app users.
# Source: https://stackoverflow.com/a/31436781/6763239
# See also: https://github.com/chapmanu/imposter/blob/development/devops/ansible/roles/ssh/tasks/main.yml
- name: Add users to sshd_config AllowUsers line
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ ansible_user }} {{ app_user }} root"
  become: yes
  notify: Reload ssh service

# SSH keys
# https://github.com/jcalazan/ansible-django-stack/issues/11#issuecomment-60548736

- name: Duplicate the SSH public key file
  become_user: deploy
  copy: src="~/.ssh/id_rsa.pub"
        dest="~/.ssh/id_rsa.pub"
        mode=0644

- name: Duplicate the SSH private key file
  become_user: deploy
  copy: src="~/.ssh/id_rsa"
        dest="~/.ssh/id_rsa"
        mode=0600

- name: Duplicate the Known host file
  become_user: deploy
  copy: src=~/.ssh/known_hosts
        dest=~/.ssh/known_hosts
        mode=0600