---
# This should be filled out and placed in /chap-press/config/database.yml
# This file is *only* used to generate wp-config.php
staging:
  host: 'localhost' 
  database: 'chappress_dev' 
  username: 'chappress'
  password: 'chappress'

