---
#
# Ansible Requirement Files
# Imports third-party roles.
#
# Usage:
#   ansible-galaxy install -r requirements.yml
#
# References:
# - https://stackoverflow.com/a/30176625/6763239
# - http://docs.ansible.com/ansible/latest/galaxy.html#installing-multiple-roles-from-a-file
#

# Avoid issues with time skew.
- src: geerlingguy.ntp

# Sets up user accounts.
- src: ontic.account

# Self-signed certificates for vm/staging servers.
- src: jdauphant.ssl-certs

# Install Composer, the PHP Dependency Manager
- src: geerlingguy.composer

# Install and configure MySQL or MariaDB server
- src: geerlingguy.mysql

# Install nginx webserver.
- src: geerlingguy.nginx

# Deploy PHP 7 (php-fpm) for nginx 
- src: chusiang.php7

# Manages firewall.
- src: geerlingguy.firewall
