---
#
# To run playbook:
#   cd devops/ansible
#   ansible-playbook webserver.yml -i hosts/virtualbox
#
# To run specific roles, tag the role(s) dev and use the --tags option:
#   ansible-playbook webserver.yml -i hosts/virtualbox --tags dev -v
#
# See group_vars/webserver for more info on each role.
#
- name: Install MariaDB, Nginx, PHP70, Composer & SSL
  hosts: webserver
  become: true

  roles:
    - { role: geerlingguy.mysql,    tags: ['mariadb'] }
    - { role: geerlingguy.repo-epel, tags: ['epel'] }
    - { role: geerlingguy.nginx,    tags: ['nginx'] }
    - { role: chusiang.php7,        tags: ['php70'] }
    # - { role: jdauphant.ssl-certs,  tags: ['ssl'] }
    - { role: tjarrett.selfsignedcertificate, when: use_self_signed_cert, tags: ['ssl'] }
    - { role: geerlingguy.composer, tags: ['composer'] }
    - { role: ontic.account,        tags: ['ontic'] }
    - { role: basic-packages,       tags: ['basic'] }
    
