---
- name: Install Common Packages
  yum: name=git state=present

# WP CLI
- name: Check if wp-cli is installed
  stat: path=/usr/local/bin/wp
  register: wp_file

# Install wp-cli if file isn't located
- name: download wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp
  when: not wp_file.stat.exists

- name: update permissions of wp-cli to allow anyone to execute it
  file: path=/usr/local/bin/wp mode=0755

# Template for nginx server
- name: Copy nginx server configuration
  template: 
    src: "chappress-default.conf.j2" 
    dest: "/etc/nginx/conf.d/chappress-default.conf"
  notify: restart nginx

# WORDPRESS CONFIGURATIONS

# Create directories
- name: Create www directory
  file: state=directory path="/var/www" 

- name: Create html directory
  file: state=directory path="/var/www/html" 

# Set permissions
- name: Set group permissions for webadmin at server root
  file: path=/var/www/html owner=root group=deploy # command: chown -v root:deploy /var/www/html

- name: Set file permissions at server root
  file: path=/var/www/html recurse=yes mode=2775  # command: chmod 2775 /var/www/html -Rv

# Create WordPress DB
- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} login_user=root state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present
