---
ssl_certs_country: "US"
ssl_certs_locality: "California"
ssl_certs_organization: "Chapman University"
ssl_certs_state: "California"
ssl_certs_common_name: "chappress-staging"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"

ssl_certs_path: "/etc/ssl"
ssl_certs_path_owner: "wimops"
ssl_certs_path_group: "root"
ssl_certs_privkey_path: "/etc/ssl/private/chappress-staging.key"
ssl_certs_cert_path: "/etc/ssl/certs/chappress-staging.pem"
ssl_certs_csr_path: "/etc/ssl/certs/chappress-staging.csr"
ssl_certs_dhparam_path: "/etc/ssl/certs/dhparam.pem"
ssl_certs_mode: "0700"
ssl_certs_force_replace: yes

ssl_certs_local_privkey_path: "{{inventory_dir|default(playbook_dir)}}/files/ssl/chappress-staging.key"
ssl_certs_local_cert_path: "{{inventory_dir|default(playbook_dir)}}/files/ssl/chappress-staging.pem"
ssl_certs_local_privkey_data: ""
ssl_certs_local_cert_data: ""

ssl_certs_generate_self_signed: true
ssl_certs_key_size: "2048"
ssl_certs_generate_dh_param: true
ssl_certs_dhparam_size: "2048"