---
# This playbook will install MariaDB and create db user and give permissions.
# https://github.com/ansible/ansible-examples/tree/master/wordpress-nginx_rhel7
# 
# Note: SELinux (Security-Enhanced Linux) adds an extra layer of security and 
# prevents programs from accessing files, directories or ports unless 
# it is configured to access those resources.

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

# Chapman staging servers defaults to disabled. 
# https://mariadb.com/kb/en/mariadb/what-to-do-if-mariadb-doesnt-start/#selinux 
- name: Enable SELinux at next reboot
  selinux:
    state: permissive
    policy: targeted

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

